#!/usr/bin/env python3
#
# See also: http://alestic.com/2014/11/aws-lambda-shell
#
# Usage:
#   export LAMBDASH_FUNCTION=[FUNCTIONNAME]
#   lambdash [SHELLCOMMAND]
# 
import boto3, json, sys, os, base64, shlex

command = ' '.join(shlex.quote(arg) for arg in sys.argv[1:])

response = boto3.client('lambda').invoke(
    InvocationType='RequestResponse',
    FunctionName=os.environ.get('LAMBDASH_FUNCTION') or 'lambdash',
    Payload=json.dumps({'command': command}))
result = json.load(response['Payload'])

os.write(sys.stdout.fileno(), base64.b64decode(result['stdout']))
os.write(sys.stderr.fileno(), base64.b64decode(result['stderr']))

if result['error'] and 'code' in result['error']:
    exit(result['error']['code'])
exit(0)
